### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by rexjohannes** [typeqgroup/cyte-tracker#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Bug:

Man kann den Bot einladen wenn man rechtsklick im dev mode auf ihn mach und die id copyiert.
Zum fixen einfach Bot auf Privat machen.

**Comment by rexjohannes** [comment]
https://imgur.com/UD1xNRd

**Comment by rexjohannes** [comment]
https://imgur.com/mT7oHpb

**Comment by rexjohannes** [comment]
ID: 642025454009843722

Invite: https://discordapp.com/oauth2/authorize?client_id=642025454009843722&permissions=0&scope=bot

**Comment by lukasl-dev** [comment]
already fixed.
